# These are supported funding model platforms
#
# Funding for OldRepublicDevs/PyKotor
# Support the OldRepublicDevs organization and its core maintainers:
# - th3w1zard1 (Boden): Core maintainer and project lead
# - NickHugi (Nicholas Hugi): Core maintainer and original developer
#
# Note: Both maintainers must have GitHub Sponsors enabled for their profiles
# to appear in the sponsor button. The organization (OldRepublicDevs) will
# appear if it has GitHub Sponsors enabled.

github: [th3w1zard1, NickHugi]

