# Auto-label PRs based on changed files
# Format for actions/labeler@v5
libraries:
  - changed-files:
    - any-glob-to-any-file: 'Libraries/**/*'
  
tools:
  - changed-files:
    - any-glob-to-any-file: 'Tools/**/*'
  
tests:
  - changed-files:
    - any-glob-to-any-file: 'tests/**/*'
  
docs:
  - changed-files:
    - any-glob-to-any-file:
      - 'docs/**/*'
      - 'README.md'
      - 'CONTRIBUTING.md'
      - '*.md'
      - 'wiki/**/*'

ci:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/**/*'
      - '.github/workflows/**/*'

dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - 'pyproject.toml'
      - 'requirements*.txt'
      - '**/requirements.txt'
      - '**/pyproject.toml'

python:
  - changed-files:
    - any-glob-to-any-file: '**/*.py'
