# GitHub Support file for repository health
# See: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file

# This file helps GitHub understand how to route support requests
# It's used by GitHub's support system to provide better help
