# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\widgets\resource_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets

from qtpy.QtCore import QSize, QMetaObject, QCoreApplication


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(333, 364)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sectionCombo = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sectionCombo.sizePolicy().hasHeightForWidth())
        self.sectionCombo.setSizePolicy(sizePolicy)
        self.sectionCombo.setMaxVisibleItems(18)
        self.sectionCombo.setObjectName("sectionCombo")
        self.horizontalLayout_2.addWidget(self.sectionCombo)
        self.refreshButton = QtWidgets.QPushButton(Form)
        self.refreshButton.setMinimumSize(QSize(70, 0))
        self.refreshButton.setMaximumSize(QSize(16777215, 70))
        self.refreshButton.setObjectName("refreshButton")
        self.horizontalLayout_2.addWidget(self.refreshButton)
        self.horizontalLayout_2.setStretch(0, 4)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.searchEdit = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchEdit.sizePolicy().hasHeightForWidth())
        self.searchEdit.setSizePolicy(sizePolicy)
        self.searchEdit.setObjectName("searchEdit")
        self.horizontalLayout_4.addWidget(self.searchEdit)
        self.reloadButton = QtWidgets.QPushButton(Form)
        self.reloadButton.setEnabled(True)
        self.reloadButton.setMinimumSize(QSize(70, 0))
        self.reloadButton.setMaximumSize(QSize(70, 16777215))
        self.reloadButton.setObjectName("reloadButton")
        self.horizontalLayout_4.addWidget(self.reloadButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.resourceTree = RobustTreeView(Form)
        self.resourceTree.setAlternatingRowColors(True)
        self.resourceTree.setSortingEnabled(True)
        self.resourceTree.setAllColumnsShowFocus(True)
        self.resourceTree.setObjectName("resourceTree")
        self.resourceTree.header().setSortIndicatorShown(True)
        self.resourceTree.header().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.resourceTree)

        self.retranslateUi(Form)
        QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.refreshButton.setToolTip(_translate("Form", "Refresh this list."))
        self.refreshButton.setText(_translate("Form", "Refresh"))
        self.searchEdit.setPlaceholderText(_translate("Form", "search..."))
        self.reloadButton.setToolTip(_translate("Form", "Reload the active module/folder."))
        self.reloadButton.setText(_translate("Form", "Reload"))
from utility.ui_libraries.qt.widgets.itemviews.treeview import RobustTreeView
