# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\editors\ifo.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabBasic = QtWidgets.QWidget()
        self.tabBasic.setObjectName("tabBasic")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tabBasic)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBoxIdentity = QtWidgets.QGroupBox(self.tabBasic)
        self.groupBoxIdentity.setObjectName("groupBoxIdentity")
        self.formLayoutIdentity = QtWidgets.QFormLayout(self.groupBoxIdentity)
        self.formLayoutIdentity.setObjectName("formLayoutIdentity")
        self.labelModName = QtWidgets.QLabel(self.groupBoxIdentity)
        self.labelModName.setObjectName("labelModName")
        self.formLayoutIdentity.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelModName)
