# Form implementation generated from reading ui file '..\ui\dialogs\extract_options.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_ExtractOptionsDialog(object):
    def setupUi(self, ExtractOptionsDialog):
        ExtractOptionsDialog.setObjectName("ExtractOptionsDialog")
        ExtractOptionsDialog.resize(300, 200)
        self.verticalLayout = QtWidgets.QVBoxLayout(ExtractOptionsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tpcGroup = QtWidgets.QGroupBox(parent=ExtractOptionsDialog)
        self.tpcGroup.setObjectName("tpcGroup")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tpcGroup)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tpcDecompileCheckbox = QtWidgets.QCheckBox(parent=self.tpcGroup)
        self.tpcDecompileCheckbox.setObjectName("tpcDecompileCheckbox")
        self.verticalLayout_2.addWidget(self.tpcDecompileCheckbox)
        self.tpcTxiCheckbox = QtWidgets.QCheckBox(parent=self.tpcGroup)
        self.tpcTxiCheckbox.setObjectName("tpcTxiCheckbox")
        self.verticalLayout_2.addWidget(self.tpcTxiCheckbox)
        self.verticalLayout.addWidget(self.tpcGroup)
        self.mdlGroup = QtWidgets.QGroupBox(parent=ExtractOptionsDialog)
        self.mdlGroup.setObjectName("mdlGroup")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.mdlGroup)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.mdlDecompileCheckbox = QtWidgets.QCheckBox(parent=self.mdlGroup)
        self.mdlDecompileCheckbox.setEnabled(True)
        self.mdlDecompileCheckbox.setObjectName("mdlDecompileCheckbox")
        self.verticalLayout_3.addWidget(self.mdlDecompileCheckbox)
        self.mdlTexturesCheckbox = QtWidgets.QCheckBox(parent=self.mdlGroup)
        self.mdlTexturesCheckbox.setObjectName("mdlTexturesCheckbox")
        self.verticalLayout_3.addWidget(self.mdlTexturesCheckbox)
        self.verticalLayout.addWidget(self.mdlGroup)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=ExtractOptionsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ExtractOptionsDialog)
        self.buttonBox.accepted.connect(ExtractOptionsDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(ExtractOptionsDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ExtractOptionsDialog)

    def retranslateUi(self, ExtractOptionsDialog):
        _translate = QtCore.QCoreApplication.translate
        ExtractOptionsDialog.setWindowTitle(_translate("ExtractOptionsDialog", "Extract Options"))
        self.tpcGroup.setTitle(_translate("ExtractOptionsDialog", "TPC Options"))
        self.tpcDecompileCheckbox.setText(_translate("ExtractOptionsDialog", "Decompile"))
        self.tpcTxiCheckbox.setText(_translate("ExtractOptionsDialog", "Extract TXI"))
        self.mdlGroup.setTitle(_translate("ExtractOptionsDialog", "MDL Options"))
        self.mdlDecompileCheckbox.setToolTip(_translate("ExtractOptionsDialog", "Decompile MDL to ASCII format"))
        self.mdlDecompileCheckbox.setText(_translate("ExtractOptionsDialog", "Decompile"))
        self.mdlTexturesCheckbox.setText(_translate("ExtractOptionsDialog", "Extract Textures"))
