# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\dialogs\indoor_downloader.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 350)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.downloadAllButton = QtWidgets.QPushButton(Dialog)
        self.downloadAllButton.setObjectName("downloadAllButton")
        self.gridLayout.addWidget(self.downloadAllButton, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Kit Downloader"))
        self.groupBox.setTitle(_translate("Dialog", "Available Kits"))
        self.downloadAllButton.setText(_translate("Dialog", "Download All Kits"))
        self.downloadAllButton.setToolTip(_translate("Dialog", "Download all kits at once from a single archive"))
