# Form implementation generated from reading ui file '..\ui\dialogs\insert_instance.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftPanelLayout = QtWidgets.QVBoxLayout()
        self.leftPanelLayout.setObjectName("leftPanelLayout")
        self.previewGroup = QtWidgets.QGroupBox(parent=Dialog)
        self.previewGroup.setObjectName("previewGroup")
        self.previewLayout = QtWidgets.QVBoxLayout(self.previewGroup)
        self.previewLayout.setObjectName("previewLayout")
