# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\windows\module_designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(970, 651)
        MainWindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.lockInstancesCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.lockInstancesCheck.setMaximumSize(QtCore.QSize(28, 16777215))
        self.lockInstancesCheck.setStyleSheet("QCheckbox { spacing: 0px; }\n"
"                                        QCheckBox::indicator {\n"
"                                        image: url(:/images/icons/lock.png);\n"
"                                        border: 1px solid rgba(30, 144, 255, 0.0);\n"
"                                        width: 26px;\n"
"                                        height: 26px;\n"
"                                        }\n"
"                                        QCheckBox::indicator:unchecked:hover {\n"
"                                        background: rgba(30, 144, 255, 0.2);\n"
"                                        border: 1px solid rgba(30, 144, 255, 0.4);\n"
"                                        }\n"
"                                        QCheckBox::indicator:checked {\n"
"                                        background: rgba(30, 144, 255, 0.4);\n"
"                                        border:1px solid rgba(30, 144, 255, 0.6);\n"
"                                        }\n"
"                                        QCheckBox::indicator:checked:hover {\n"
"                                        background: rgba(30, 144, 255, 0.5);\n"
"                                        border:1px solid rgba(30, 144, 255, 0.7);\n"
"                                        }")
        self.lockInstancesCheck.setText("")
        self.lockInstancesCheck.setChecked(False)
        self.lockInstancesCheck.setObjectName("lockInstancesCheck")
        self.horizontalLayout_2.addWidget(self.lockInstancesCheck)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.cursorCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.cursorCheck.setMaximumSize(QtCore.QSize(28, 16777215))
        self.cursorCheck.setStyleSheet("QCheckbox {\n"
"                                        spacing: 0px;\n"
"                                        }\n"
"\n"
"                                        QCheckBox::indicator {\n"
"                                        image: url(:/images/icons/cursor.png);\n"
"                                        border: 1px solid rgba(30, 144, 255, 0.0);\n"
"                                        width: 26px;\n"
"                                        height: 26px;\n"
"                                        }\n"
"\n"
"                                        QCheckBox::indicator:unchecked:hover {\n"
"                                        background: rgba(30, 144, 255, 0.2);\n"
"                                        border: 1px solid rgba(30, 144, 255, 0.4);\n"
"                                        }\n"
"\n"
"                                        QCheckBox::indicator:checked {\n"
"                                        background: rgba(30, 144, 255, 0.4);\n"
"                                        border:1px solid rgba(30, 144, 255, 0.6);\n"
"                                        }\n"
"\n"
"                                        QCheckBox::indicator:checked:hover {\n"
"                                        background: rgba(30, 144, 255, 0.5);\n"
"                                        border:1px solid rgba(30, 144, 255, 0.7);\n"
"                                        }\n"
"\n"
"                                    ")
        self.cursorCheck.setText("")
        self.cursorCheck.setChecked(True)
        self.cursorCheck.setObjectName("cursorCheck")
        self.horizontalLayout_2.addWidget(self.cursorCheck)
        self.backfaceCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.backfaceCheck.setMaximumSize(QtCore.QSize(28, 16777215))
        self.backfaceCheck.setStyleSheet("QCheckbox {\n"
"                                        spacing: 0px;\n"
"                                        }\n"
"\n"
"                                        QCheckBox::indicator {\n"
"                                        image: url(:/images/icons/backface.png);\n"
"                                        border: 1px solid rgba(30, 144, 255, 0.0);\n"
"                                        width: 26px;\n"
"                                        height: 26px;\n"
"                                        }\n"
"\n"
"                                        QCheckBox::indicator:unchecked:hover {\n"
"                                        background: rgba(30, 144, 255, 0.2);\n"
"                                        border: 1px solid rgba(30, 144, 255, 0.4);\n"
"                                        }\n"
"\n"
"                                        QCheckBox::indicator:checked {\n"
"                                        background: rgba(30, 144, 255, 0.4);\n"
"                                        border:1px solid rgba(30, 144, 255, 0.6);\n"
"                                        }\n"
"\n"
"                                        QCheckBox::indicator:checked:hover {\n"
"                                        background: rgba(30, 144, 255, 0.5);\n"
"                                        border:1px solid rgba(30, 144, 255, 0.7);\n"
"                                        }\n"
"\n"
"                                    ")
        self.backfaceCheck.setText("")
        self.backfaceCheck.setChecked(True)
        self.backfaceCheck.setObjectName("backfaceCheck")
        self.horizontalLayout_2.addWidget(self.backfaceCheck)
        self.lightmapCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.lightmapCheck.setMaximumSize(QtCore.QSize(28, 16777215))
        self.lightmapCheck.setStyleSheet("QCheckbox {\n"
"                                        spacing: 0px;\n"
"                                        }\n"
"\n"
"                                        QCheckBox::indicator {\n"
"                                        image: url(:/images/icons/lightmap.png);\n"
"                                        border: 1px solid rgba(30, 144, 255, 0.0);\n"
"                                        width: 26px;\n"
"                                        height: 26px;\n"
"                                        }\n"
"\n"
"                                        QCheckBox::indicator:unchecked:hover {\n"
"                                        background: rgba(30, 144, 255, 0.2);\n"
"                                        border: 1px solid rgba(30, 144, 255, 0.4);\n"
"                                        }\n"
"\n"
"                                        QCheckBox::indicator:checked {\n"
"                                        background: rgba(30, 144, 255, 0.4);\n"
"                                        border:1px solid rgba(30, 144, 255, 0.6);\n"
"                                        }\n"
"\n"
"                                        QCheckBox::indicator:checked:hover {\n"
"                                        background: rgba(30, 144, 255, 0.5);\n"
"                                        border:1px solid rgba(30, 144, 255, 0.7);\n"
"                                        }\n"
"\n"
"                                    ")
        self.lightmapCheck.setText("")
        self.lightmapCheck.setChecked(True)
        self.lightmapCheck.setObjectName("lightmapCheck")
        self.horizontalLayout_2.addWidget(self.lightmapCheck)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.viewCreatureCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.viewCreatureCheck.setMaximumSize(QtCore.QSize(28, 16777215))
        self.viewCreatureCheck.setStyleSheet("QCheckbox {\n"
"                                        spacing: 0px;\n"
"                                        }\n"
"\n"
"                                        QCheckBox::indicator {\n"
"                                        image: url(:/images/icons/k1/creature.png);\n"
"                                        border: 1px solid rgba(30, 144, 255, 0.0);\n"
"                                        width: 26px;\n"
"                                        height: 26px;\n"
"                                        }\n"
"\n"
"                                        QCheckBox::indicator:unchecked:hover {\n"
"                                        background: rgba(30, 144, 255, 0.2);\n"
"                                        border: 1px solid rgba(30, 144, 255, 0.4);\n"
"                                        }\n"
"\n"
"                                        QCheckBox::indicator:checked {\n"
"                                        background: rgba(30, 144, 255, 0.4);\n"
"                                        border:1px solid rgba(30, 144, 255, 0.6);\n"
"                                        }\n"
"\n"
"                                        QCheckBox::indicator:checked:hover {\n"
"                                        background: rgba(30, 144, 255, 0.5);\n"
"                                        border:1px solid rgba(30, 144, 255, 0.7);\n"
"                                        }\n"
"\n"
"                                    ")
        self.viewCreatureCheck.setText("")
        self.viewCreatureCheck.setChecked(True)
        self.viewCreatureCheck.setObjectName("viewCreatureCheck")
        self.horizontalLayout_2.addWidget(self.viewCreatureCheck)
        self.viewDoorCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.viewDoorCheck.setMaximumSize(QtCore.QSize(28, 16777215))
        self.viewDoorCheck.setStyleSheet("QCheckBox::indicator {\n"
"                                        image: url(:/images/icons/k1/door.png);\n"
"                                        border: 1px solid rgba(30, 144, 255, 0.0);\n"
"                                        width: 26px;\n"
"                                        height: 26px;\n"
"                                        }\n"
"\n"
"                                        QCheckBox::indicator:unchecked:hover {\n"
"                                        background: rgba(30, 144, 255, 0.2);\n"
"                                        border: 1px solid rgba(30, 144, 255, 0.4);\n"
"                                        }\n"
"\n"
"                                        QCheckBox::indicator:checked {\n"
"                                        background: rgba(30, 144, 255, 0.4);\n"
"                                        border:1px solid rgba(30, 144, 255, 0.6);\n"
"                                        }\n"
"\n"
"                                        QCheckBox::indicator:checked:hover {\n"
"                                        background: rgba(30, 144, 255, 0.5);\n"
"                                        border:1px solid rgba(30, 144, 255, 0.7);\n"
"                                        }\n"
"\n"
"                                    ")
        self.viewDoorCheck.setText("")
        self.viewDoorCheck.setChecked(True)
        self.viewDoorCheck.setObjectName("viewDoorCheck")
        self.horizontalLayout_2.addWidget(self.viewDoorCheck)
        self.viewPlaceableCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.viewPlaceableCheck.setMaximumSize(QtCore.QSize(28, 16777215))
        self.viewPlaceableCheck.setStyleSheet("QCheckBox::indicator {\n"
"                                        image: url(:/images/icons/k1/placeable.png);\n"
"                                        border: 1px solid rgba(30, 144, 255, 0.0);\n"
"                                        width: 26px;\n"
"                                        height: 26px;\n"
"                                        }\n"
"\n"
"                                        QCheckBox::indicator:unchecked:hover {\n"
"                                        background: rgba(30, 144, 255, 0.2);\n"
"                                        border: 1px solid rgba(30, 144, 255, 0.4);\n"
"                                        }\n"
"\n"
"                                        QCheckBox::indicator:checked {\n"
"                                        background: rgba(30, 144, 255, 0.4);\n"
"                                        border:1px solid rgba(30, 144, 255, 0.6);\n"
"                                        }\n"
"\n"
"                                        QCheckBox::indicator:checked:hover {\n"
"                                        background: rgba(30, 144, 255, 0.5);\n"
"                                        border:1px solid rgba(30, 144, 255, 0.7);\n"
"                                        }\n"
"\n"
"                                    ")
        self.viewPlaceableCheck.setText("")
        self.viewPlaceableCheck.setChecked(True)
        self.viewPlaceableCheck.setObjectName("viewPlaceableCheck")
        self.horizontalLayout_2.addWidget(self.viewPlaceableCheck)
        self.viewStoreCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.viewStoreCheck.setMaximumSize(QtCore.QSize(28, 16777215))
        self.viewStoreCheck.setStyleSheet("QCheckBox::indicator {\n"
"                                        image: url(:/images/icons/k1/merchant.png);\n"
"                                        border: 1px solid rgba(30, 144, 255, 0.0);\n"
"                                        width: 26px;\n"
"                                        height: 26px;\n"
"                                        }\n"
"\n"
"                                        QCheckBox::indicator:unchecked:hover {\n"
"                                        background: rgba(30, 144, 255, 0.2);\n"
"                                        border: 1px solid rgba(30, 144, 255, 0.4);\n"
"                                        }\n"
"\n"
"                                        QCheckBox::indicator:checked {\n"
"                                        background: rgba(30, 144, 255, 0.4);\n"
"                                        border:1px solid rgba(30, 144, 255, 0.6);\n"
"                                        }\n"
"\n"
"                                        QCheckBox::indicator:checked:hover {\n"
"                                        background: rgba(30, 144, 255, 0.5);\n"
"                                        border:1px solid rgba(30, 144, 255, 0.7);\n"
"                                        }\n"
"\n"
"                                    ")
        self.viewStoreCheck.setText("")
        self.viewStoreCheck.setChecked(True)
        self.viewStoreCheck.setObjectName("viewStoreCheck")
        self.horizontalLayout_2.addWidget(self.viewStoreCheck)
        self.viewSoundCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.viewSoundCheck.setMaximumSize(QtCore.QSize(28, 16777215))
        self.viewSoundCheck.setStyleSheet("QCheckBox::indicator {\n"
"                                        image: url(:/images/icons/k1/sound.png);\n"
"                                        border: 1px solid rgba(30, 144, 255, 0.0);\n"
"                                        width: 26px;\n"
"                                        height: 26px;\n"
"                                        }\n"
"\n"
"                                        QCheckBox::indicator:unchecked:hover {\n"
"                                        background: rgba(30, 144, 255, 0.2);\n"
"                                        border: 1px solid rgba(30, 144, 255, 0.4);\n"
"                                        }\n"
"\n"
"                                        QCheckBox::indicator:checked {\n"
"                                        background: rgba(30, 144, 255, 0.4);\n"
"                                        border:1px solid rgba(30, 144, 255, 0.6);\n"
"                                        }\n"
"\n"
"                                        QCheckBox::indicator:checked:hover {\n"
"                                        background: rgba(30, 144, 255, 0.5);\n"
"                                        border:1px solid rgba(30, 144, 255, 0.7);\n"
"                                        }\n"
"\n"
"                                    ")
        self.viewSoundCheck.setText("")
        self.viewSoundCheck.setChecked(True)
        self.viewSoundCheck.setObjectName("viewSoundCheck")
        self.horizontalLayout_2.addWidget(self.viewSoundCheck)
        self.viewWaypointCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.viewWaypointCheck.setMaximumSize(QtCore.QSize(28, 16777215))
        self.viewWaypointCheck.setStyleSheet("QCheckBox::indicator {\n"
"                                        image: url(:/images/icons/k1/waypoint.png);\n"
"                                        border: 1px solid rgba(30, 144, 255, 0.0);\n"
"                                        width: 26px;\n"
"                                        height: 26px;\n"
"                                        }\n"
"\n"
"                                        QCheckBox::indicator:unchecked:hover {\n"
"                                        background: rgba(30, 144, 255, 0.2);\n"
"                                        border: 1px solid rgba(30, 144, 255, 0.4);\n"
"                                        }\n"
"\n"
"                                        QCheckBox::indicator:checked {\n"
"                                        background: rgba(30, 144, 255, 0.4);\n"
"                                        border:1px solid rgba(30, 144, 255, 0.6);\n"
"                                        }\n"
"\n"
"                                        QCheckBox::indicator:checked:hover {\n"
"                                        background: rgba(30, 144, 255, 0.5);\n"
"                                        border:1px solid rgba(30, 144, 255, 0.7);\n"
"                                        }\n"
"\n"
"                                    ")
        self.viewWaypointCheck.setText("")
        self.viewWaypointCheck.setChecked(True)
        self.viewWaypointCheck.setObjectName("viewWaypointCheck")
        self.horizontalLayout_2.addWidget(self.viewWaypointCheck)
        self.viewCameraCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.viewCameraCheck.setMaximumSize(QtCore.QSize(28, 16777215))
        self.viewCameraCheck.setStyleSheet("QCheckBox::indicator {\n"
"                                        image: url(:/images/icons/k1/camera.png);\n"
"                                        border: 1px solid rgba(30, 144, 255, 0.0);\n"
"                                        width: 26px;\n"
"                                        height: 26px;\n"
"                                        }\n"
"\n"
"                                        QCheckBox::indicator:unchecked:hover {\n"
"                                        background: rgba(30, 144, 255, 0.2);\n"
"                                        border: 1px solid rgba(30, 144, 255, 0.4);\n"
"                                        }\n"
"\n"
"                                        QCheckBox::indicator:checked {\n"
"                                        background: rgba(30, 144, 255, 0.4);\n"
"                                        border:1px solid rgba(30, 144, 255, 0.6);\n"
"                                        }\n"
"\n"
"                                        QCheckBox::indicator:checked:hover {\n"
"                                        background: rgba(30, 144, 255, 0.5);\n"
"                                        border:1px solid rgba(30, 144, 255, 0.7);\n"
"                                        }\n"
"\n"
"                                    ")
        self.viewCameraCheck.setText("")
        self.viewCameraCheck.setChecked(True)
        self.viewCameraCheck.setObjectName("viewCameraCheck")
        self.horizontalLayout_2.addWidget(self.viewCameraCheck)
        self.viewEncounterCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.viewEncounterCheck.setMaximumSize(QtCore.QSize(28, 16777215))
        self.viewEncounterCheck.setStyleSheet("QCheckBox::indicator {\n"
"                                        image: url(:/images/icons/k1/encounter.png);\n"
"                                        border: 1px solid rgba(30, 144, 255, 0.0);\n"
"                                        width: 26px;\n"
"                                        height: 26px;\n"
"                                        }\n"
"\n"
"                                        QCheckBox::indicator:unchecked:hover {\n"
"                                        background: rgba(30, 144, 255, 0.2);\n"
"                                        border: 1px solid rgba(30, 144, 255, 0.4);\n"
"                                        }\n"
"\n"
"                                        QCheckBox::indicator:checked {\n"
"                                        background: rgba(30, 144, 255, 0.4);\n"
"                                        border:1px solid rgba(30, 144, 255, 0.6);\n"
"                                        }\n"
"\n"
"                                        QCheckBox::indicator:checked:hover {\n"
"                                        background: rgba(30, 144, 255, 0.5);\n"
"                                        border:1px solid rgba(30, 144, 255, 0.7);\n"
"                                        }\n"
"\n"
"                                    ")
        self.viewEncounterCheck.setText("")
        self.viewEncounterCheck.setChecked(True)
        self.viewEncounterCheck.setObjectName("viewEncounterCheck")
        self.horizontalLayout_2.addWidget(self.viewEncounterCheck)
        self.viewTriggerCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.viewTriggerCheck.setMaximumSize(QtCore.QSize(28, 16777215))
        self.viewTriggerCheck.setStyleSheet("QCheckBox::indicator {\n"
"                                        image: url(:/images/icons/k1/trigger.png);\n"
"                                        border: 1px solid rgba(30, 144, 255, 0.0);\n"
"                                        width: 26px;\n"
"                                        height: 26px;\n"
"                                        }\n"
"\n"
"                                        QCheckBox::indicator:unchecked:hover {\n"
"                                        background: rgba(30, 144, 255, 0.2);\n"
"                                        border: 1px solid rgba(30, 144, 255, 0.4);\n"
"                                        }\n"
"\n"
"                                        QCheckBox::indicator:checked {\n"
"                                        background: rgba(30, 144, 255, 0.4);\n"
"                                        border:1px solid rgba(30, 144, 255, 0.6);\n"
"                                        }\n"
"\n"
"                                        QCheckBox::indicator:checked:hover {\n"
"                                        background: rgba(30, 144, 255, 0.5);\n"
"                                        border:1px solid rgba(30, 144, 255, 0.7);\n"
"                                        }\n"
"\n"
"                                    ")
        self.viewTriggerCheck.setText("")
        self.viewTriggerCheck.setChecked(True)
        self.viewTriggerCheck.setObjectName("viewTriggerCheck")
        self.horizontalLayout_2.addWidget(self.viewTriggerCheck)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftPanel = QtWidgets.QTabWidget(self.centralwidget)
        self.leftPanel.setMaximumSize(QtCore.QSize(250, 16777215))
        self.leftPanel.setObjectName("leftPanel")
        self.resourceTab = QtWidgets.QWidget()
        self.resourceTab.setObjectName("resourceTab")
        self.resourceTabLayout = QtWidgets.QVBoxLayout(self.resourceTab)
        self.resourceTabLayout.setObjectName("resourceTabLayout")
        self.resourceTree = QtWidgets.QTreeWidget(self.resourceTab)
        self.resourceTree.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.resourceTree.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.resourceTree.setHeaderHidden(True)
        self.resourceTree.setObjectName("resourceTree")
        self.resourceTree.headerItem().setText(0, "1")
        self.resourceTabLayout.addWidget(self.resourceTree)
        self.leftPanel.addTab(self.resourceTab, "")
        self.lytTab = QtWidgets.QWidget()
        self.lytTab.setObjectName("lytTab")
        self.lytTabLayout = QtWidgets.QVBoxLayout(self.lytTab)
        self.lytTabLayout.setObjectName("lytTabLayout")
        self.lytToolbar = QtWidgets.QToolBar(self.lytTab)
        self.lytToolbar.setObjectName("lytToolbar")
        self.lytTabLayout.addWidget(self.lytToolbar)
        self.lytSplitter = QtWidgets.QSplitter(self.lytTab)
        self.lytSplitter.setOrientation(QtCore.Qt.Vertical)
        self.lytSplitter.setObjectName("lytSplitter")
        self.lytTree = QtWidgets.QTreeWidget(self.lytSplitter)
        self.lytTree.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.lytTree.setHeaderHidden(True)
        self.lytTree.setObjectName("lytTree")
        self.lytElementTabs = QtWidgets.QTabWidget(self.lytSplitter)
        self.lytElementTabs.setObjectName("lytElementTabs")
        self.roomTab = QtWidgets.QWidget()
        self.roomTab.setObjectName("roomTab")
        self.roomLayout = QtWidgets.QFormLayout(self.roomTab)
        self.roomLayout.setObjectName("roomLayout")
        self.modelLabel = QtWidgets.QLabel(self.roomTab)
        self.modelLabel.setObjectName("modelLabel")
        self.roomLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.modelLabel)
        self.modelLayout = QtWidgets.QHBoxLayout()
        self.modelLayout.setObjectName("modelLayout")
        self.modelEdit = QtWidgets.QLineEdit(self.roomTab)
        self.modelEdit.setObjectName("modelEdit")
        self.modelLayout.addWidget(self.modelEdit)
        self.browseModelButton = QtWidgets.QToolButton(self.roomTab)
        self.browseModelButton.setObjectName("browseModelButton")
        self.modelLayout.addWidget(self.browseModelButton)
        self.roomLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.modelLayout)
        self.positionLabel = QtWidgets.QLabel(self.roomTab)
        self.positionLabel.setObjectName("positionLabel")
        self.roomLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.positionLabel)
        self.positionLayout = QtWidgets.QHBoxLayout()
        self.positionLayout.setObjectName("positionLayout")
        self.posXSpin = QtWidgets.QDoubleSpinBox(self.roomTab)
        self.posXSpin.setDecimals(3)
        self.posXSpin.setMinimum(-10000.0)
        self.posXSpin.setMaximum(10000.0)
        self.posXSpin.setObjectName("posXSpin")
        self.positionLayout.addWidget(self.posXSpin)
        self.posYSpin = QtWidgets.QDoubleSpinBox(self.roomTab)
        self.posYSpin.setDecimals(3)
        self.posYSpin.setMinimum(-10000.0)
        self.posYSpin.setMaximum(10000.0)
        self.posYSpin.setObjectName("posYSpin")
        self.positionLayout.addWidget(self.posYSpin)
        self.posZSpin = QtWidgets.QDoubleSpinBox(self.roomTab)
        self.posZSpin.setDecimals(3)
        self.posZSpin.setMinimum(-10000.0)
        self.posZSpin.setMaximum(10000.0)
        self.posZSpin.setObjectName("posZSpin")
        self.positionLayout.addWidget(self.posZSpin)
        self.roomLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.positionLayout)
        self.rotationLabel = QtWidgets.QLabel(self.roomTab)
        self.rotationLabel.setObjectName("rotationLabel")
        self.roomLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.rotationLabel)
        self.rotationLayout = QtWidgets.QHBoxLayout()
        self.rotationLayout.setObjectName("rotationLayout")
        self.rotXSpin = QtWidgets.QDoubleSpinBox(self.roomTab)
        self.rotXSpin.setDecimals(3)
        self.rotXSpin.setMinimum(-360.0)
        self.rotXSpin.setMaximum(360.0)
        self.rotXSpin.setObjectName("rotXSpin")
        self.rotationLayout.addWidget(self.rotXSpin)
        self.rotYSpin = QtWidgets.QDoubleSpinBox(self.roomTab)
        self.rotYSpin.setDecimals(3)
        self.rotYSpin.setMinimum(-360.0)
        self.rotYSpin.setMaximum(360.0)
        self.rotYSpin.setObjectName("rotYSpin")
        self.rotationLayout.addWidget(self.rotYSpin)
        self.rotZSpin = QtWidgets.QDoubleSpinBox(self.roomTab)
        self.rotZSpin.setDecimals(3)
        self.rotZSpin.setMinimum(-360.0)
        self.rotZSpin.setMaximum(360.0)
        self.rotZSpin.setObjectName("rotZSpin")
        self.rotationLayout.addWidget(self.rotZSpin)
        self.roomLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.rotationLayout)
        self.lytElementTabs.addTab(self.roomTab, "")
        self.doorHookTab = QtWidgets.QWidget()
        self.doorHookTab.setObjectName("doorHookTab")
        self.doorHookLayout = QtWidgets.QFormLayout(self.doorHookTab)
        self.doorHookLayout.setObjectName("doorHookLayout")
        self.roomNameLabel = QtWidgets.QLabel(self.doorHookTab)
        self.roomNameLabel.setObjectName("roomNameLabel")
        self.doorHookLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.roomNameLabel)
        self.roomNameCombo = QtWidgets.QComboBox(self.doorHookTab)
        self.roomNameCombo.setObjectName("roomNameCombo")
        self.doorHookLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.roomNameCombo)
        self.doorNameLabel = QtWidgets.QLabel(self.doorHookTab)
        self.doorNameLabel.setObjectName("doorNameLabel")
        self.doorHookLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.doorNameLabel)
        self.doorNameEdit = QtWidgets.QLineEdit(self.doorHookTab)
        self.doorNameEdit.setObjectName("doorNameEdit")
        self.doorHookLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.doorNameEdit)
        self.lytElementTabs.addTab(self.doorHookTab, "")
        self.lytTabLayout.addWidget(self.lytSplitter)
        self.leftPanel.addTab(self.lytTab, "")
        self.horizontalLayout.addWidget(self.leftPanel)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.mainRenderer = ModuleRenderer(self.splitter)
        self.mainRenderer.setMouseTracking(True)
        self.mainRenderer.setObjectName("mainRenderer")
        self.flatRenderer = WalkmeshRenderer(self.splitter)
        self.flatRenderer.setMouseTracking(True)
        self.flatRenderer.setObjectName("flatRenderer")
        self.verticalLayout_2.addWidget(self.splitter)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.instanceList = QtWidgets.QListWidget(self.centralwidget)
        self.instanceList.setMaximumSize(QtCore.QSize(200, 16777215))
        self.instanceList.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.instanceList.setObjectName("instanceList")
        self.horizontalLayout.addWidget(self.instanceList)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 970, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionAddRoom = QtWidgets.QAction(MainWindow)
        self.actionAddRoom.setObjectName("actionAddRoom")
        self.actionAddDoorHook = QtWidgets.QAction(MainWindow)
        self.actionAddDoorHook.setObjectName("actionAddDoorHook")
        self.actionAddTrack = QtWidgets.QAction(MainWindow)
        self.actionAddTrack.setObjectName("actionAddTrack")
        self.actionAddObstacle = QtWidgets.QAction(MainWindow)
        self.actionAddObstacle.setObjectName("actionAddObstacle")
        self.actionImportTexture = QtWidgets.QAction(MainWindow)
        self.actionImportTexture.setObjectName("actionImportTexture")
        self.actionGenerateWalkmesh = QtWidgets.QAction(MainWindow)
        self.actionGenerateWalkmesh.setObjectName("actionGenerateWalkmesh")
        self.actionInstructions = QtWidgets.QAction(MainWindow)
        self.actionInstructions.setObjectName("actionInstructions")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionHide3DView = QtWidgets.QAction(MainWindow)
        self.actionHide3DView.setObjectName("actionHide3DView")
        self.actionHide2DView = QtWidgets.QAction(MainWindow)
        self.actionHide2DView.setObjectName("actionHide2DView")
        self.lytToolbar.addAction(self.actionAddRoom)
        self.lytToolbar.addAction(self.actionAddDoorHook)
        self.lytToolbar.addAction(self.actionAddTrack)
        self.lytToolbar.addAction(self.actionAddObstacle)
        self.lytToolbar.addSeparator()
        self.lytToolbar.addAction(self.actionImportTexture)
        self.lytToolbar.addAction(self.actionGenerateWalkmesh)
        self.lytToolbar.addAction(self.actionAddRoom)
        self.lytToolbar.addAction(self.actionAddDoorHook)
        self.lytToolbar.addAction(self.actionAddTrack)
        self.lytToolbar.addAction(self.actionAddObstacle)
        self.lytToolbar.addSeparator()
        self.lytToolbar.addAction(self.actionImportTexture)
        self.lytToolbar.addAction(self.actionGenerateWalkmesh)
        self.lytToolbar.addAction(self.actionAddRoom)
        self.lytToolbar.addAction(self.actionAddDoorHook)
        self.lytToolbar.addAction(self.actionAddTrack)
        self.lytToolbar.addAction(self.actionAddObstacle)
        self.lytToolbar.addSeparator()
        self.lytToolbar.addAction(self.actionImportTexture)
        self.lytToolbar.addAction(self.actionGenerateWalkmesh)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionUndo)
        self.menuFile.addAction(self.actionRedo)
        self.menuHelp.addAction(self.actionInstructions)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionRedo.setShortcut(_translate("MainWindow", "Ctrl+Y"))
        self.actionRedo.setShortcut(_translate("MainWindow", "Ctrl+Shift+Z"))
        self.lockInstancesCheck.setToolTip(_translate("MainWindow", "Lock all instances in place"))
        self.cursorCheck.setToolTip(_translate("MainWindow", "Display cursor at mouse"))
        self.backfaceCheck.setToolTip(_translate("MainWindow", "Enable backface culling"))
        self.lightmapCheck.setToolTip(_translate("MainWindow", "Enable lightmaps"))
        self.viewCreatureCheck.setToolTip(_translate("MainWindow", "Creatures"))
        self.viewDoorCheck.setToolTip(_translate("MainWindow", "Doors"))
        self.viewPlaceableCheck.setToolTip(_translate("MainWindow", "Placeables"))
        self.viewStoreCheck.setToolTip(_translate("MainWindow", "Merchants"))
        self.viewSoundCheck.setToolTip(_translate("MainWindow", "Sounds"))
        self.viewWaypointCheck.setToolTip(_translate("MainWindow", "Waypoints"))
        self.viewCameraCheck.setToolTip(_translate("MainWindow", "Cameras"))
        self.viewEncounterCheck.setToolTip(_translate("MainWindow", "Encounters"))
        self.viewTriggerCheck.setToolTip(_translate("MainWindow", "Triggers"))
        self.leftPanel.setTabText(self.leftPanel.indexOf(self.resourceTab), _translate("MainWindow", "Resources"))
        self.lytTree.headerItem().setText(0, _translate("MainWindow", "Layout Elements"))
        self.modelLabel.setText(_translate("MainWindow", "Model:"))
        self.browseModelButton.setText(_translate("MainWindow", "..."))
        self.positionLabel.setText(_translate("MainWindow", "Position:"))
        self.rotationLabel.setText(_translate("MainWindow", "Rotation:"))
        self.lytElementTabs.setTabText(self.lytElementTabs.indexOf(self.roomTab), _translate("MainWindow", "Room"))
        self.roomNameLabel.setText(_translate("MainWindow", "Room:"))
        self.doorNameLabel.setText(_translate("MainWindow", "Door:"))
        self.lytElementTabs.setTabText(self.lytElementTabs.indexOf(self.doorHookTab), _translate("MainWindow", "Door Hook"))
        self.leftPanel.setTabText(self.leftPanel.indexOf(self.lytTab), _translate("MainWindow", "Layout"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionSave.setText(_translate("MainWindow", "Save GIT"))
        self.actionAddRoom.setText(_translate("MainWindow", "Add Room"))
        self.actionAddRoom.setToolTip(_translate("MainWindow", "Add a new room to the layout"))
        self.actionAddDoorHook.setText(_translate("MainWindow", "Add Door Hook"))
        self.actionAddDoorHook.setToolTip(_translate("MainWindow", "Add a new door hook"))
        self.actionAddTrack.setText(_translate("MainWindow", "Add Track"))
        self.actionAddTrack.setToolTip(_translate("MainWindow", "Add a new track element"))
        self.actionAddObstacle.setText(_translate("MainWindow", "Add Obstacle"))
        self.actionAddObstacle.setToolTip(_translate("MainWindow", "Add a new obstacle"))
        self.actionImportTexture.setText(_translate("MainWindow", "Import Texture"))
        self.actionImportTexture.setToolTip(_translate("MainWindow", "Import a custom texture"))
        self.actionGenerateWalkmesh.setText(_translate("MainWindow", "Generate Walkmesh"))
        self.actionGenerateWalkmesh.setToolTip(_translate("MainWindow", "Generate walkmesh from room layout"))
        self.actionInstructions.setText(_translate("MainWindow", "Instructions"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionHide3DView.setText(_translate("MainWindow", "Hide 3D View"))
        self.actionHide2DView.setText(_translate("MainWindow", "Hide 2D View"))
from toolset.gui.widgets.renderer.module import ModuleRenderer
from toolset.gui.widgets.renderer.walkmesh import WalkmeshRenderer
import resources_rc
